swagger: "2.0"
info:
  title: "User API"
  version: "1.0.0"

basePath: "/api/v1"

schemes:
  - "http"

paths:
  /users:
    get:
      tags:
        - "users"
      summary: "Get all users"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"

definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
